#!/bin/bash
clear
echo """$(tput setaf 2)
 |==========================================================|$(tput setaf 1)[v1.5]$(tput setaf 2)
 | _________  ___                                 _ _     _ |=====|
 | |  ___|  \/  |           $(tput setaf 1)-by ~Z30X~$(tput setaf 2)           | (_)   | |  P   |
 | | |_  | .  . |  ___  ___  _   _ _ __ ___ ___  | |_ ___| |_ <>  |
 | |  _| | |\/| | / __|/ _ \| | | |_'__/ __/ _ \ | | / __| __| K  |
 | | |_  | |  | | \__ \ (_) | |_| |_| | (_|  __/ | | \__ \ |_  >< |
 | \_(_) \_|  |_/ |___/\___/ \__,_|_|  \___\___| |_|_|___/\__|  G |
 |================================================================|
$(tput setaf 1)	      \Contract me for any idea to add \ bugs/
$(tput setaf 2)               ======================================
$(tput setaf 1)                       \ ZeoxSEC@gmail.com /
$(tput sgr 0)"""
sleep 3
clear
while :
do
    clear
    cat<<EOF
 $(tput setaf 2)|======================|$(tput sgr 0)
 $(tput setaf 2)|$(tput sgr 0) [+] Select Options : $(tput setaf 2)|$(tput sgr 0)
 $(tput setaf 2)|======================| $(tput sgr 0)
    ($(tput setaf 2)1$(tput sgr 0)) All In OnePKG
    ($(tput setaf 2)2$(tput sgr 0)) Update SystemPKG
    ($(tput setaf 2)3$(tput sgr 0)) Upgrade SystemPKG
    ($(tput setaf 2)4$(tput sgr 0)) Full Upgrade SystemPKG
    ($(tput setaf 2)5$(tput sgr 0)) Fix Missing SystemPKG
    ($(tput setaf 2)6$(tput sgr 0)) See Upgradable list (Befor upgrade)
    ($(tput setaf 2)7$(tput sgr 0)) View SourceList
    ($(tput setaf 2)8$(tput sgr 0)) Edit Sourcelist
    ($(tput setaf 2)9$(tput sgr 0)) Install Packets
    ($(tput setaf 2)0$(tput sgr 0)) Uninstall Packets
  ($(tput setaf 4)C$(tput sgr 0))heck - Verify that there are no broken dependencies
  ($(tput setaf 4)F$(tput sgr 0))reashclam ClamAV antivirus + rootkits
  ($(tput setaf 4)M$(tput sgr 0))etasploit dbupdate ($(tput setaf 1)*msf framework requierd*$(tput sgr 0))
  ($(tput setaf 4)D$(tput sgr 0)) print Metasploit data base list of installed updates
  ($(tput setaf 4)S$(tput sgr 0))ecret keep youself hidden and CHANGE MAC plese...
  ($(tput setaf 4)A$(tput sgr 0))rchive of repsitoreis favor list
  $(tput setaf 1)(Q)uit/Exit$(tput sgr 0)

EOF
read -n1 -s
case "$REPLY" in
	"1") clear && echo """$(tput setaf 1) ++++++++++++++++++ $(tput sgr 0)
 Starting UPDATE...
$(tput setaf 1) ++++++++++++++++++ $(tput sgr 0)"""
	     sudo apt-get update && sudo apt-get -y full-upgrade
	     echo """ $(tput setaf 2) 
 [!] FINISHD Press any Key to go back...$(tput sgr 0)""" && read -n 1 ;;
	"2") sudo apt-get update
	     echo """ $(tput setaf 2) 
 [!] FINISHD Press any Key to go back...$(tput sgr 0)""" && read -n 1 ;;
	"3") sudo apt-get upgrade
	     echo """ $(tput setaf 2) 
 [!] FINISHD Press any Key to go back...$(tput sgr 0)""" && read -n 1 ;;
	"4") sudo apt-get full-upgrade
	     echo """ $(tput setaf 2) 
 [!] FINISHD Press any Key to go back...$(tput sgr 0)""" && read -n 1 ;;
	"5") sudo apt-get install --fix-missing && sudo apt-get 
	     echo """ $(tput setaf 2) 
 [!] FINISHD Press any Key to go back...$(tput sgr 0)""" && read -n 1 ;;
	"6") sudo apt list --upgradable ;;
	"7") clear
		 echo """     ----------------------
 [$] My SYSTEM sources list
     ----------------------""" && read -n 1
         cat /./etc/apt/sources.list ;;
	"8") apt edit-sources ;;
	"9") echo "Type the Source/Packet name you want to install\get"
		read varname && apt-get install $varname ;;
	"0") echo "Type the Source/Packet name you want to uninstall"
		read varname && apt-get remove $varname ;;
	"C") echo "Type the Source/Packet for checking..."
		read varname && apt-get check $varname ;;
	"c") echo "Type the Source/Packet for checking..."
		 read varname && apt-get check $varname ;;
	"F") freshclam ;;
	"f") freshclam ;;
	"M") sudo searchsploit -u && echo """ $(tput setaf 2) 
 [!] FINISHD Press any Key to go back...$(tput sgr 0)""" && read -n 1 ;;
	"m") sudo searchsploit -u && echo """ $(tput setaf 2) 
 [!] FINISHD Press any Key to go back...$(tput sgr 0)""" && read -n 1 ;;
	"S") echo " [!] $(tput setaf 1)Avinables Interfaces$(tput sgr 0)"
		ifconfig | grep flags && echo """ 
 [+] $(tput setaf 1)Enter the Interface to change [+] RANDOM [+]$(tput sgr 0)"""
		read varname && sudo macchanger --random  $varname
		echo "Your new Interface MAC : select |==>> "$varname
		sleep 3.5 ;;
	"D") sudo searchsploit update
		 echo "FINISHD Press any Key to go back..." && read -n 1 ;;
	"d") sudo searchsploit update  &&
		"FINISHD Press any Key to go back..." read -n 1 ;;
	"A") clear && echo '''~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Great Place to Update from:
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
 [+] INFO: repo URLS list for Add-on your ./etc/apt/source.list
     =======================================================================
 [*] (Kali repository):
   +URL >>>''' echo "$(tput setaf 1)[https://docs.kali.org/general-use/kali-linux-sources-list-repositories]$(tput sgr 0)"
echo ''' [*] (Parrot repository):
   +URL >>>''' echo "$(tput setaf 1)[https://archive.parrotsec.org/parrot/README.html]$(tput sgr 0)"
echo ''' [*] (Debian security):
   +URL >>>''' echo "$(tput setaf 1)[https://www.debian.org/security/]$(tput sgr 0)"
echo ''' [*] (Debian repository):
   +URL >>>''' echo "$(tput setaf 1)[https://wiki.debian.org/SourcesList]$(tput sgr 0)"
echo ''' [*] (Ubuntu repository):
  +URL >>>''' echo "$(tput setaf 1)[https://help.ubuntu.com/community/Repositories/CommandLine]$(tput sgr 0)"
echo '''[*] (Ubuntu trusty re):
  +URL >>>''' echo "$(tput setaf 1)[https://packages.ubuntu.com/trusty]$(tput sgr 0)"
echo ''' ===========================
 Press any Key to go back...
 ===========================''' && read -n 1 ;;
	"Q") echo " [$(tput setaf 1)*$(tput sgr 0)] $(tput setaf 2)Thanks for using F.M sourcelist PKG$(tput sgr 0) [$(tput setaf 1)*$(tput sgr 0)]"
		sleep 2 && clear && exit ;;
	"q") echo " [$(tput setaf 1)*$(tput sgr 0)] $(tput setaf 2)Thanks for using F.M sourcelist PKG$(tput sgr 0) [$(tput setaf 1)*$(tput sgr 0)]"
		sleep 2 && clear && exit ;;
	* )  echo " [$(tput setaf 1)!$(tput sgr 0)] invalid option" ;;
    esac
    sleep 1
done
